name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Yandex Cloud Docker Registry
        uses: yc-actions/yc-cr-login@v1
        with:
            yc-sa-json-credentials: ${{ secrets.YC_SERVICE_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |-
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:r${{ github.run_number }}a${{ github.run_attempt }}
            cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.DOCKER_HUB_REPO }}:r${{ github.run_number }}a${{ github.run_attempt }}
          platforms: linux/amd64
  
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SERVICE_KEY }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.YC_CONTAINER_ACC }}
          revision-cores: 1
          revision-memory: 128Mb
          revision-core-fraction: 5
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.DOCKER_HUB_REPO }}:r${{ github.run_number }}a${{ github.run_attempt }}
          revision-execution-timeout: 16
          revision-provisioned: 1
          revision-env: |-
            KEY_PEM_PASS=${{ secrets.DEPLOY_KEY_CER_PWD }}
