name: Release

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Use tmpfs in order to build arm/v7 and linux/386 images
        # https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/109
      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 12

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Yandex Cloud Docker Registry
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
            yc-sa-json-credentials: ${{ secrets.YC_SERVICE_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |-
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ github.sha }}
            cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.DOCKER_HUB_REPO }}:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest_buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest_buildcache,mode=max
  
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SERVICE_KEY }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER }}
          revision-service-account-id: ${{ secrets.YC_CONTAINER_ACC }}
          revision-cores: 1
          revision-memory: 128Mb
          revision-core-fraction: 5
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY }}/${{ secrets.DOCKER_HUB_REPO }}:${{ github.sha }}
          revision-execution-timeout: 16
          revision-provisioned: 1
          revision-env: |-
            KEY_PEM_PASS=${{ secrets.DEPLOY_KEY_CER_PWD }}
